"""initial schema

Revision ID: 2d19039fe5f4
Revises: 
Create Date: 2026-09-02 17:17:27.517688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d19039fe5f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_action_ts', ['action', 'ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_ts'), ['ts'], unique=False)

    op.create_table('compression_records',
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('original_bytes', sa.Integer(), nullable=False),
    sa.Column('compressed_bytes', sa.Integer(), nullable=False),
    sa.Column('reduction_pct', sa.Float(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('template_count', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=48), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compression_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compression_records_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compression_records_ts'), ['ts'], unique=False)

    op.create_table('log_sources',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('adapter', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('connection_status', sa.String(length=24), nullable=False),
    sa.Column('last_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('events_processed', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_sources_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_sources_name'), ['name'], unique=True)

    op.create_table('parser_packs',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('format', sa.String(length=48), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('latest_version', sa.String(length=24), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parser_packs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parser_packs_name'), ['name'], unique=True)

    op.create_table('pii_settings',
    sa.Column('mode', sa.String(length=24), nullable=False),
    sa.Column('protect_ip', sa.Boolean(), nullable=False),
    sa.Column('protect_email', sa.Boolean(), nullable=False),
    sa.Column('protect_username', sa.Boolean(), nullable=False),
    sa.Column('protect_host', sa.Boolean(), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('token_length', sa.Integer(), nullable=False),
    sa.Column('store_reverse_map', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_runs',
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=False),
    sa.Column('stages', sa.JSON(), nullable=False),
    sa.Column('final_event', sa.JSON(), nullable=False),
    sa.Column('pii_mode', sa.String(length=24), nullable=False),
    sa.Column('saved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_runs_ts'), ['ts'], unique=False)

    op.create_table('roles',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('security_alerts',
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('rule_key', sa.String(length=48), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('risk_breakdown', sa.JSON(), nullable=False),
    sa.Column('entity', sa.JSON(), nullable=False),
    sa.Column('related_event_ids', sa.JSON(), nullable=False),
    sa.Column('affected_hosts', sa.JSON(), nullable=False),
    sa.Column('recommended_response', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=36), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dedup_key', sa.String(length=200), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_alerts_dedup_key'), ['dedup_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_alerts_risk_score'), ['risk_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_alerts_rule_key'), ['rule_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_alerts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_alerts_ts'), ['ts'], unique=False)

    op.create_table('security_events',
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('detection_type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('verdict', sa.String(length=24), nullable=False),
    sa.Column('raw_reference', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_events_detection_type'), ['detection_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_ts'), ['ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_verdict'), ['verdict'], unique=False)

    op.create_table('security_rules',
    sa.Column('rule_key', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('window_seconds', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_rules_rule_key'), ['rule_key'], unique=True)

    op.create_table('templates',
    sa.Column('template_key', sa.String(length=24), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('token_signature', sa.String(length=64), nullable=False),
    sa.Column('example', sa.Text(), nullable=False),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_templates_template_key'), ['template_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_templates_token_signature'), ['token_signature'], unique=False)

    op.create_table('parser_versions',
    sa.Column('pack_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=24), nullable=False),
    sa.Column('schema_version', sa.String(length=8), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('wasm_module_b64', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('validation_report', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['parser_packs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parser_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parser_versions_pack_id'), ['pack_id'], unique=False)

    op.create_table('processing_jobs',
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('source_name', sa.String(length=120), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('declared_format', sa.String(length=48), nullable=True),
    sa.Column('detected_format', sa.String(length=48), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('processed_records', sa.Integer(), nullable=False),
    sa.Column('invalid_records', sa.Integer(), nullable=False),
    sa.Column('duplicate_records', sa.Integer(), nullable=False),
    sa.Column('quarantined_records', sa.Integer(), nullable=False),
    sa.Column('processing_rate', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['log_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processing_jobs_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_name', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_name'], ['roles.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('raw_logs',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('security_verdict', sa.String(length=24), nullable=False),
    sa.Column('processing_errors', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_logs_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_logs_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_logs_source_name'), ['source_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_logs_status'), ['status'], unique=False)
        batch_op.create_index('ix_rawlog_job_line', ['job_id', 'line_number'], unique=False)
        batch_op.create_index('ix_rawlog_job_status', ['job_id', 'status'], unique=False)

    op.create_table('normalized_events',
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('raw_log_id', sa.String(length=36), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('destination_ip', sa.String(length=64), nullable=True),
    sa.Column('source_port', sa.Integer(), nullable=True),
    sa.Column('destination_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=16), nullable=True),
    sa.Column('action', sa.String(length=48), nullable=True),
    sa.Column('status', sa.String(length=48), nullable=True),
    sa.Column('process', sa.String(length=128), nullable=True),
    sa.Column('service', sa.String(length=128), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('field_confidence', sa.JSON(), nullable=False),
    sa.Column('raw_log', sa.Text(), nullable=False),
    sa.Column('parser', sa.String(length=64), nullable=False),
    sa.Column('parser_version', sa.String(length=24), nullable=False),
    sa.Column('schema_version', sa.String(length=8), nullable=False),
    sa.Column('pii_protected', sa.Boolean(), nullable=False),
    sa.Column('pii_mode', sa.String(length=24), nullable=False),
    sa.Column('processing_status', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('template_id', sa.String(length=24), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ),
    sa.ForeignKeyConstraint(['raw_log_id'], ['raw_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('normalized_events', schema=None) as batch_op:
        batch_op.create_index('ix_event_host_ts', ['host', 'timestamp'], unique=False)
        batch_op.create_index('ix_event_severity_ts', ['severity', 'timestamp'], unique=False)
        batch_op.create_index('ix_event_source_ts', ['source', 'timestamp'], unique=False)
        batch_op.create_index('ix_event_src_ip_ts', ['source_ip', 'timestamp'], unique=False)
        batch_op.create_index('ix_event_type_ts', ['event_type', 'timestamp'], unique=False)
        batch_op.create_index('ix_event_user_ts', ['username', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_events_destination_ip'), ['destination_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_events_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_events_host'), ['host'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_events_ingested_at'), ['ingested_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_events_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_events_processing_status'), ['processing_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_events_raw_log_id'), ['raw_log_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_events_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_events_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_events_source_ip'), ['source_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_events_template_id'), ['template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_events_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_events_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('normalized_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_normalized_events_username'))
        batch_op.drop_index(batch_op.f('ix_normalized_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_normalized_events_template_id'))
        batch_op.drop_index(batch_op.f('ix_normalized_events_source_ip'))
        batch_op.drop_index(batch_op.f('ix_normalized_events_source'))
        batch_op.drop_index(batch_op.f('ix_normalized_events_severity'))
        batch_op.drop_index(batch_op.f('ix_normalized_events_raw_log_id'))
        batch_op.drop_index(batch_op.f('ix_normalized_events_processing_status'))
        batch_op.drop_index(batch_op.f('ix_normalized_events_job_id'))
        batch_op.drop_index(batch_op.f('ix_normalized_events_ingested_at'))
        batch_op.drop_index(batch_op.f('ix_normalized_events_host'))
        batch_op.drop_index(batch_op.f('ix_normalized_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_normalized_events_email'))
        batch_op.drop_index(batch_op.f('ix_normalized_events_destination_ip'))
        batch_op.drop_index(batch_op.f('ix_normalized_events_action'))
        batch_op.drop_index('ix_event_user_ts')
        batch_op.drop_index('ix_event_type_ts')
        batch_op.drop_index('ix_event_src_ip_ts')
        batch_op.drop_index('ix_event_source_ts')
        batch_op.drop_index('ix_event_severity_ts')
        batch_op.drop_index('ix_event_host_ts')

    op.drop_table('normalized_events')
    with op.batch_alter_table('raw_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_rawlog_job_status')
        batch_op.drop_index('ix_rawlog_job_line')
        batch_op.drop_index(batch_op.f('ix_raw_logs_status'))
        batch_op.drop_index(batch_op.f('ix_raw_logs_source_name'))
        batch_op.drop_index(batch_op.f('ix_raw_logs_job_id'))
        batch_op.drop_index(batch_op.f('ix_raw_logs_content_hash'))

    op.drop_table('raw_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_source_id'))

    op.drop_table('processing_jobs')
    with op.batch_alter_table('parser_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parser_versions_pack_id'))

    op.drop_table('parser_versions')
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_templates_token_signature'))
        batch_op.drop_index(batch_op.f('ix_templates_template_key'))

    op.drop_table('templates')
    with op.batch_alter_table('security_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_rules_rule_key'))

    op.drop_table('security_rules')
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_events_verdict'))
        batch_op.drop_index(batch_op.f('ix_security_events_ts'))
        batch_op.drop_index(batch_op.f('ix_security_events_severity'))
        batch_op.drop_index(batch_op.f('ix_security_events_job_id'))
        batch_op.drop_index(batch_op.f('ix_security_events_detection_type'))

    op.drop_table('security_events')
    with op.batch_alter_table('security_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_alerts_ts'))
        batch_op.drop_index(batch_op.f('ix_security_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_security_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_security_alerts_rule_key'))
        batch_op.drop_index(batch_op.f('ix_security_alerts_risk_score'))
        batch_op.drop_index(batch_op.f('ix_security_alerts_dedup_key'))

    op.drop_table('security_alerts')
    op.drop_table('roles')
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_ts'))

    op.drop_table('pipeline_runs')
    op.drop_table('pii_settings')
    with op.batch_alter_table('parser_packs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parser_packs_name'))

    op.drop_table('parser_packs')
    with op.batch_alter_table('log_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_sources_name'))
        batch_op.drop_index(batch_op.f('ix_log_sources_category'))

    op.drop_table('log_sources')
    with op.batch_alter_table('compression_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compression_records_ts'))
        batch_op.drop_index(batch_op.f('ix_compression_records_job_id'))

    op.drop_table('compression_records')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_ts'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index('ix_audit_action_ts')

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
