"""response simulations table (Checkpoint 8)

Revision ID: ad333f8a9e5c
Revises: e464ee2c777b
Create Date: 2026-09-06 00:34:16.734409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad333f8a9e5c'
down_revision: Union[str, None] = 'e464ee2c777b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_simulations',
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('alert_title', sa.String(length=200), nullable=False),
    sa.Column('alert_rule_key', sa.String(length=48), nullable=True),
    sa.Column('alert_severity', sa.String(length=16), nullable=False),
    sa.Column('alert_risk_score', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.JSON(), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('simulation_only', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['security_alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('response_simulations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_response_simulations_alert_id'), ['alert_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_simulations_ts'), ['ts'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response_simulations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_response_simulations_ts'))
        batch_op.drop_index(batch_op.f('ix_response_simulations_alert_id'))

    op.drop_table('response_simulations')
    # ### end Alembic commands ###
