"""template mining and compression tables (Checkpoint 6)

Adds template_matches; extends templates (shape/variables/timestamps) and
compression_records (measured benchmark fields). All Phase 2-13 tables were
already present in the initial migration - this revision only covers the
Checkpoint 6 additions.

Revision ID: e464ee2c777b
Revises: 2d19039fe5f4
Create Date: 2026-09-05 18:19:06.329061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e464ee2c777b'
down_revision: Union[str, None] = '2d19039fe5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_matches',
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('raw_log_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=False),
    sa.Column('separators', sa.JSON(), nullable=True),
    sa.Column('trailing', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['raw_log_id'], ['raw_logs.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('template_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_template_matches_raw_log_id'), ['raw_log_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_template_matches_template_id'), ['template_id'], unique=False)

    # server_default values below make these NOT NULL adds safe on tables that
    # may already hold rows (e.g. an existing docker-compose Postgres volume).
    with op.batch_alter_table('compression_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata_bytes', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('total_compressed_bytes', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('reconstructable_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('processing_seconds', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('events_per_sec', sa.Float(), nullable=False, server_default='0'))

    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('literal_tokens', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('variable_types', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('separators', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('trailing', sa.String(length=64), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('variable_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('source_distribution', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('examples', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=False,
                                       server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False,
                                       server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.drop_column('source')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('examples')
        batch_op.drop_column('source_distribution')
        batch_op.drop_column('variable_count')
        batch_op.drop_column('trailing')
        batch_op.drop_column('separators')
        batch_op.drop_column('variable_types')
        batch_op.drop_column('literal_tokens')
        batch_op.drop_column('token_count')

    with op.batch_alter_table('compression_records', schema=None) as batch_op:
        batch_op.drop_column('events_per_sec')
        batch_op.drop_column('processing_seconds')
        batch_op.drop_column('reconstructable_count')
        batch_op.drop_column('total_compressed_bytes')
        batch_op.drop_column('metadata_bytes')

    with op.batch_alter_table('template_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_template_matches_template_id'))
        batch_op.drop_index(batch_op.f('ix_template_matches_raw_log_id'))

    op.drop_table('template_matches')
    # ### end Alembic commands ###
